version: '3'
services:
  elasticsearch:
    networks:
    - esnetwork
    env_file:
    - es.env
    container_name: "elasticsearch"
    ports:
    - "9200:9200"
    - "9300:9300"
    image: "elasticsearch:6.5.4"
  kibana:
    networks:
    - esnetwork
    container_name: "kibana"
    ports:
    - "5601:5601"
    image: "kibana:6.5.4"
networks:
  esnetwork: